vrpn_client_node:
  ros__parameters:
    server: 192.168.0.33
    port: 3883
    frame_id: "world"
    use_server_time: false
    refresh_tracker_frequency: 1.0
    #update_frequency: 30.0
    broadcast_tf: true
